PREFIX lex: <http://purl.org/lex#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX sao: <http://salt.semanticauthoring.org/ontologies/sao#>
PREFIX sdo: <http://salt.semanticauthoring.org/ontologies/sdo#>

PREFIX exp: <{{"param": "resource", "filter": "RemoveLTGT"}}>

CONSTRUCT {
  exp: ?pred ?obj .
  ?subj ?pred2 exp: .
  ?par a ?type .
}

FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz>
FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz/updates>
FROM <http://linked.opendata.cz/resource/dataset/legislation/cz/uz>
FROM <http://linked.opendata.cz/resource/dataset/legislation/psp.cz>

WHERE {
 exp: a frbr:Expression.
 exp: frbr:realizationOf ?par.
 ?par a ?type.
 exp: ?pred ?obj.
 ?subj ?pred2 exp: .
}