PREFIX lex: <http://purl.org/lex#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX sao: <http://salt.semanticauthoring.org/ontologies/sao#>
PREFIX sdo: <http://salt.semanticauthoring.org/ontologies/sdo#>
PREFIX results: <http://>

CONSTRUCT {
 ?res dcterms:title ?title .
 ?res dcterms:issued ?date .
 ?res dcterms:subject ?subject .
 results:RESULTS results:TOTALCOUNT ?total . 
}

FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz>
FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz/updates>

WHERE {
{
  SELECT (COUNT(?totalres) as ?total)
  WHERE{?totalres a lex:Decision}
}
{
  SELECT ?res
  WHERE{?res a lex:Decision}
  OFFSET {{"param": "offset", "default": "0"}}
  LIMIT {{"param": "limit", "default": "10"}}
}
  ?res dcterms:title ?title .
  OPTIONAL { ?res dcterms:issued ?date }
  OPTIONAL { ?res dcterms:subject ?subject }

}

