PREFIX lex: <http://purl.org/lex#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX sao: <http://salt.semanticauthoring.org/ontologies/sao#>
PREFIX sdo: <http://salt.semanticauthoring.org/ontologies/sdo#>
PREFIX results: <http://>

CONSTRUCT {
 ?res ?p ?o .
 ?res ?p_pass ?subj.
 results:RESULTS results:TOTALCOUNT ?total .
}

FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz>
FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz/updates>

WHERE {
{
  SELECT (COUNT(?totalres) as ?total)
  WHERE{?totalres a lex:Decision}
}
{
  SELECT ?res
  WHERE{?res a lex:Decision}
  OFFSET {{"param": "offset", "default": "0"}}
  LIMIT {{"param": "limit", "default": "10"}}
}
  ?res ?p ?o .
  ?subj ?p2 ?res .
  BIND(IRI(CONCAT(?p2, "_PASSIVE")) AS ?p_pass).
}

