PREFIX lex: <http://purl.org/lex#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX sao: <http://salt.semanticauthoring.org/ontologies/sao#>
PREFIX sdo: <http://salt.semanticauthoring.org/ontologies/sdo#>
PREFIX odcs: <http://linked.opendata.cz/ontology/odcs/xmlValue>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX x: <http://>

PREFIX dec: <{{"param": "resource", "filter": "RemoveLTGT"}}>

CONSTRUCT {
  dec: dcterms:creator ?creator.
  dec: dcterms:creatorTitles ?creatorTitle .
  dec: dcterms:subject ?subject .
  dec: dcterms:title ?title .
  dec: dcterms:issued ?issued .
  dec: dcterms:identifier ?identifier .
  dec: lex:belongsToFile ?file .
  dec: lex:fileKind ?fileKind .
  dec: lex:fileNumber ?fileNumber .
  dec: lex:fileYear ?fileYear .
  dec: lex:senateNumber ?senateNumber .
  dec: skos:catLabel ?deccatlabel .
  dec: skos:kindLabel ?deckindlabel .
}

FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz>
FROM <http://linked.opendata.cz/resource/dataset/legislation/nsoud.cz/updates>
#FROM <http://linked.opendata.cz/resource/dataset/legislation/cz/uz>
#FROM <http://linked.opendata.cz/resource/dataset/legislation/psp.cz>

WHERE {
  dec: dcterms:title ?title .
  OPTIONAL {
    dec: dcterms:creator ?creator .
    ?creator dcterms:title ?creatorTitle .
  }
  OPTIONAL { dec: dcterms:subject ?subject . }
  OPTIONAL { dec: dcterms:issued ?issued . }
  OPTIONAL { dec: dcterms:identifier ?identifier . }
  OPTIONAL { dec: lex:belongsToFile ?file . }
  OPTIONAL {
    ?file lex:fileKind ?fileKind .
    ?file lex:fileNumber ?fileNumber .
    ?file lex:fileYear ?fileYear .
    ?file lex:senateNumber ?senateNumber .
  }  
  OPTIONAL {
    dec: lex:decisionCategory ?deccat .
    ?deccat skos:prefLabel ?deccatlabel .
  }
  OPTIONAL {
    dec: lex:decisionKind ?deckind .
    ?deckind skos:prefLabel ?deckindlabel .
  }
}
