PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX lex: <http://purl.org/lex#>
PREFIX dcterms: <http://purl.org/dc/terms/>

PREFIX resource: <{{"param": "resource", "filter": "RemoveLTGT"}}>

CONSTRUCT{
?expr dcterms:valid ?valid.
?expr dcterms:actID ?actID.
?expr dcterms:amendmentID ?amendmentId.
?expr dcterms:exprID ?exprID.
?expr frbr:partOf ?mpartOf.
}

FROM <http://linked.opendata.cz/resource/dataset/legislation/psp.cz>
FROM NAMED <http://linked.opendata.cz/resource/dataset/legislation/cz/uz>

WHERE {
  SELECT ?expr ?valid ?actID ?exprID ?amendmentId max(?partOf) as ?mpartOf
  WHERE {
    resource: a lex:Act .
    ?expr frbr:realizationOf resource: .
    ?expr dcterms:valid ?valid.
    ?expr frbr:realizationOf/dcterms:identifier ?actID.
    OPTIONAL {
      ?expr ^lex:changeResult/^lex:definesChange/frbr:realizationOf ?amendmentId.
      ?amendmentId dcterms:identifier ?exprID.
    }
    OPTIONAL {
       GRAPH <http://linked.opendata.cz/resource/dataset/legislation/cz/uz> {?partOf frbr:partOf ?expr}
    }
  }
  ORDER BY ?valid
  OFFSET {{"param": "offset", "default": "0"}}
  LIMIT {{"param": "limit", "default": "10"}}
}