PREFIX odcs: <http://linked.opendata.cz/ontology/odcs/>
PREFIX resource: <http://linked.opendata.cz/resource/legislation/cz/act/2012/89-2012/expression/cz/act/2012/89-2012/cs>

CONSTRUCT {
    resource: odcs:htmlValue ?html .
}

FROM <http://linked.opendata.cz/resource/dataset/legislation/acts/fulltexts>

WHERE {
    resource: odcs:htmlValue ?html .
}