PREFIX frbr: <http://purl.org/vocab/frbr/core#>
PREFIX lex: <http://purl.org/lex#>
PREFIX dcterms: <http://purl.org/dc/terms/>

PREFIX resource: <{{"param": "resource", "filter": "RemoveLTGT"}}>

CONSTRUCT{
?expr dcterms:valid ?valid.
?expr dcterms:partOf ?lexExpr.
?expr dcterms:amendment ?amendment.
?expr dcterms:identifier ?amendmentId.
}

FROM <http://linked.opendata.cz/resource/dataset/legislation/psp.cz>
FROM NAMED <http://linked.opendata.cz/resource/dataset/legislation/cz/uz>

FROM NAMED <http://linked.opendata.cz/resource/dataset/legislation/psp.cz>
FROM <http://linked.opendata.cz/resource/dataset/legislation/cz/uz>

WHERE {
  SELECT DISTINCT ?expr ?lexExpr ?valid ?amendment ?amendmentId
  WHERE {
    resource: frbr:realizationOf ?section .
    ?expr frbr:realizationOf ?section .
    ?expr frbr:partOf* ?lexExpr.
    GRAPH <http://linked.opendata.cz/resource/dataset/legislation/psp.cz> { ?lexExpr dcterms:valid ?valid . 
    OPTIONAL {
      ?lexExpr ^lex:changeResult/^lex:definesChange/frbr:realizationOf ?amendment.
      ?amendment dcterms:identifier ?amendmentId.
    }
    }
  }
  ORDER BY ?valid
  OFFSET {{"param": "offset", "default": "0"}}
  LIMIT {{"param": "limit", "default": "10"}}
}
