PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX s: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ares: <http://linked.opendata.cz/ontology/ares#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX my: <http://>

CONSTRUCT{
  ?check skos:notation ?id.
  ?check dcterms:date ?date.
  ?check my:region ?region.
  ?check my:locality ?locality.
  ?check my:zipcode ?zipcode.
  ?check my:street ?street.
  ?check my:objectName ?objectName.
#  ?check my:state ?stateLabel.
#  ?check my:trade ?tradeTitle.
  ?check my:result ?result.
  
}

FROM <http://linked.opendata.cz/resource/dataset/coi.cz/kontroly>
FROM <http://linked.opendata.cz/resource/dataset/ares/basic>
FROM <http://linked.opendata.cz/resource/dataset/ares/rzp>
FROM NAMED <http://linked.opendata.cz/resource/dataset/coi.cz/sankce>
FROM NAMED <http://linked.opendata.cz/resource/dataset/coi.cz/zajisteni>
FROM NAMED <http://linked.opendata.cz/resource/dataset/coi.cz/zakazy>

WHERE {  
SELECT DISTINCT ?check ?id ?date ?locality ?zipcode ?region ?street ?objectName ?result #?tradeTitle ?stateLabel 
WHERE {
  
  {
  SELECT DISTINCT ?check ?id ?date ?locality ?zipcode ?region ?street
  WHERE {
	?check a s:CheckAction.		# just because of performance
    ?check skos:notation ?id.
    ?check s:location ?location.
    ?location s:postalCode ?zipcode.
    OPTIONAL {
    	?location a s:PostalAddress. # just because of performance
    	?location s:addressLocality ?locality.
    	?location s:addressRegion ?region.
    	#?location s:streetAddress ?street.
    }
    OPTIONAL {?location s:streetAddress ?street.}

{{"param" : "values"}}
  
  }
  ORDER BY DESC(?date)
  OFFSET {{"param": "offset", "default": "0"}}
  LIMIT {{"param": "limit", "default": "10"}}
  }

  OPTIONAL {
  	?check a s:CheckAction.		# just because of performance
    ?check s:object ?object.
    ?object gr:legalName ?objectName.
# WAITING FOR A <http://linked.opendata.cz/resource/dataset/ares/rzp> DATASET:
#    ?object regorg:orgActivity ?activity.
#    ?object ares:stav-zivnosti/skos:prefLabel ?stateLabel.	
#    ?object ares:zivnost ?zivnost.
#    ?zivnost dcterms:title ?tradeTitle.

  }
  
  OPTIONAL {
    {
    GRAPH <http://linked.opendata.cz/resource/dataset/coi.cz/sankce>{
    	?check s:result ?result.
    }
    } UNION {
    GRAPH <http://linked.opendata.cz/resource/dataset/coi.cz/zajisteni>{
    	?check s:result ?result.
    }
    } UNION {
    GRAPH <http://linked.opendata.cz/resource/dataset/coi.cz/zakazy>{
    	?check s:result ?result.
    }
    }
  }
}
}